server:
  port: 8080

spring:
  application:
    name: wine-ecommerce
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/wine_ecommerce
    username: wine_user
    password: wine_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      password: admin

logging:
  level:
    com.wine.ecommerce: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  jwt:
    secret: wine-ecommerce-secret-key-for-jwt-token-generation-must-be-at-least-256-bits
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
    issuer: wine-ecommerce